language: objective-c
script:
  - xctool -workspace CMDQueryStringSerialization.xcworkspace -scheme CMDQueryStringSerialization -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace CMDQueryStringSerialization.xcworkspace -scheme CMDQueryStringSerialization -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
